site_name: Filester
site_url: https://loum.github.io/filester/

nav:
  - Home: index.md
  - Reference:
    - filester: reference/filester.md

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - header.autohide
    - content.code.copy

watch:
  - ../src/filester
